### ISSUE TITLE
Fix Credo Warnings

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits-elixir#11]
ran: `mix credo --strict` got:
![image](https://user-images.githubusercontent.com/194400/30296505-5f64da22-973c-11e7-976c-d06ac6761cfa.png)

**Comment by nelsonic** [comment]
If anyone wants to refactor the code to respond to these issues, please go for it! 👍

**Comment by nelsonic** [comment]
`dogma` isn't adding much _value_ to this project right now ...
![image](https://user-images.githubusercontent.com/194400/36734920-d097e260-1bcc-11e8-86b7-19de4de3d74b.png)
This error is _cryptic_ and unrelated to any of the App's _functionality_ ... 😕

**Comment by nelsonic** [comment]
Dogma issues noted: https://travis-ci.org/dwyl/hits-elixir/builds/346807972
![image](https://user-images.githubusercontent.com/194400/36735310-c98e0caa-1bcd-11e8-9b8c-2553826406e1.png)

**Comment by nelsonic** [comment]
Warnings:
![image](https://user-images.githubusercontent.com/194400/36735633-84d4fe9c-1bce-11e8-9897-90c22068f17a.png)
🙄

**Comment by nelsonic** [comment]
https://travis-ci.org/dwyl/hits-elixir/builds/346812428
![image](https://user-images.githubusercontent.com/194400/36735924-38fbbfc8-1bcf-11e8-9f7a-28685ad1a58b.png)

**Comment by SimonLab** [comment]
The PR #21 should now fix the all the Credo issues.

**Comment by nelsonic** [comment]
Thanks @SimonLab 👍
