### ISSUE TITLE
Add WebSockets for Pushing Hit Data to Client

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits-elixir#13]
At present `hits-elixir` does not have WebSockets whereas `hits` does.
If you visit: http://hits.dwyl.io  (_scroll down to the "recently viewed" section_):
![image](https://user-images.githubusercontent.com/194400/30437980-f12c2190-9967-11e7-9622-cb6e49533dab.png)

Then in a `new` tab visit one of the repos/projects that has a "hit counter" badge e.g: 
https://github.com/dwyl/hapi-socketio-redis-chat-example
you will notice that it appears at the top of the list:
![image](https://user-images.githubusercontent.com/194400/30438049-1b576498-9968-11e7-95ce-7bf1078ed4cf.png)

We need to implement this in Elixir.

This looks like a good line of enquiry: https://gist.github.com/alanpeabody/4fae12b420fb50376af4
followed by: https://elixirforum.com/t/websockex-an-elixir-websocket-client/4733 (_library_)

**Comment by nelsonic** [comment]
https://github.com/meh/elixir-socket

**Comment by leordev** [comment]
I want to work on this issue! Is it still available or anyone else has picked up already?

As I saw in Contributing guidelines I should setup and discuss an Estimated Time, but I don't think we have stories and/or sprint planning right?!

How can I proceed? :)

**Comment by nelsonic** [comment]
@leordev go for it! if you have an estimate of how long you _think_ it will take you, add the label. 😉

**Comment by leordev** [comment]
Ok thanks, it's totally mine!!! 😄  
I was reading about how to build the solution and I hope to finish in the next couple hours!

**Comment by nelsonic** [comment]
done! 🎉 see: #18
