### ISSUE TITLE
Simplify coverage commands

### ISSUE THREAD

**Issue by samhstn** [dwyl/hits-elixir#24]
### What we could change:

In the `README` we currently have:

```bash
MIX_ENV=test mix do coveralls.json
```

I would suggest that this should be:

```bash
mix cover
```

We also have:

```bash
MIX_ENV=test mix coveralls.html && open cover/excoveralls.html
```

I would suggest that this should be:

```bash
mix cover.html && open cover/excoveralls.html
```

### Why this should be changed

In our [`mix.exs`](https://github.com/dwyl/hits-elixir/blob/master/mix.exs#L13) file we already specify that the preferred `MIX_ENV` is `test` for these commands, so we should remove `MIX_ENV=test`

I would quite like making use of the `aliases`, that way we can just update the aliases instead of documentation when we decide to expand what `cover` would do (for instance) (and it makes for a nicer developer experience when setting up the project).

**Comment by nelsonic** [comment]
@shouston3 agreed. go for it! 👍

**Comment by nelsonic** [comment]
Fixed by @shouston3 🎉 
closing.
